use_frameworks!

platform :ios, '10.0'

target 'SystemServiceSwift_Example' do
  pod 'SystemServiceSwift', :path => '../'

  target 'SystemServiceSwift_Tests' do
    inherit! :search_paths

    
  end
end
